### PR TITLE
CMake build with updated libraries

### PR DESCRIPTION
**Pull request by andrewGuzGRSE**
This is a new 64 bits cross-platform CMake project for ONVIF Player with updated libraries (some of them are submodules now).

What was changed in original files:
 - some OpenSSL usage due to newer version
 - some support for x64 version
 - duplicate oxfverifier - will use from parser folder, not from parserUI folder (attention - there is some difference between them)
 - EngineTest that uses not existing calcTime function
 
Most changes in src folder were done to support new OpenSSL library (tested with 3.3.1) and 64 bits.

Tested on Debian 12 and Windows 11.

For more information how to build, please, read player/README.md

### CODE REVIEW

**Review by SergeyGRSE — APPROVED** [review]

**Review by SergeyGRSE — APPROVED** [review]

**Comment by roalz** [comment]
Is there any plan to merge this PR, hopefully soon?
It makes build easier, more reliable and better automated.

**Comment by andrewGuzGRSE** [comment]
> Is there any plan to merge this PR, hopefully soon? It makes build easier, more reliable and better automated.

Hello. Unfortunately, after discussion, CMake project idea was rejected. Player will be only for Windows and Visual Studio.
If you are interested in updated version (Visual Studio 2022 and new Qt 5.12), it will be created soon.

**Comment by roalz** [comment]
I am confused... If CMake project idea was rejected, why "Cmake build #11" has been merged into v3.0?

**Comment by andrew-guz** [comment]
Sorry for that confusion.
Idea was to switch to new OpenSSL and Qt, but to work with VS2022.
Just not to lost all changes done for new OpenSSL and Qt versions, new branch was started from cmake-build brach.
As development will be finished, branch will be squash merged and no one will know about old CMake :)

**Comment by roalz** [comment]
Ok, understood (I should have looked at commits before commenting).
Still a pity to not have CMake build, at least for Visual Studio Code IDE, if not other OSes...

**Comment by andrew-guz** [comment]
Agree. Development on Linyx was easier. On the other hand, we are trying to add new library which is Meson specific and it's combination with CMake also a problem.

Anyway, not for this year, but I belive cross platform version of Player will be created. It's just not a priority for us right now.

**Pull request closed without merging**
